<a href='?action=additem_cpu'><?php echo WORDING_ITEMCATEGORY_CPU; ?></a>
<a href='?action=additem_ram'><?php echo WORDING_ITEMCATEGORY_RAM; ?></a>
<a href='?action=additem_motherboard'><?php echo WORDING_ITEMCATEGORY_MOTHERBOARD; ?></a>
<a href='?action=additem_hdd'><?php echo WORDING_ITEMCATEGORY_HDD; ?></a>
<a href='?action=additem_ssd'><?php echo WORDING_ITEMCATEGORY_SSD; ?></a>
<a href='?action=additem_case'><?php echo WORDING_ITEMCATEGORY_CASE; ?></a>
<a href='?action=additem_mouse'><?php echo WORDING_ITEMCATEGORY_MOUSE; ?></a>
<a href='?action=additem_keyboard'><?php echo WORDING_ITEMCATEGORY_KEYBOARD; ?></a>
<a href='?action=additem_screen'><?php echo WORDING_ITEMCATEGORY_SCREEN; ?></a>
<a href='?action=additem_graphicscard'><?php echo WORDING_ITEMCATEGORY_GRAPHICSCARD; ?></a>
<a href='?action=additem_cpucooler'><?php echo WORDING_ITEMCATEGORY_CPUCOOLER; ?></a>